apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-deployment
  labels:
    app: travel-with
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travel-with
  template:
    metadata:
      labels:
        app: travel-with
    spec:
      containers:
        - name: travel-with
          image: seohojun/travel-with:latest # 여기서 Docker 이미지를 사용
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ""
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
